[build]
  command = "npm run build"
  publish = "build/client"
  functions = "build/server"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 